// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Account struct {
	ID          string      `json:"id"`
	AccountType AccountType `json:"accountType"`
	Institution string      `json:"institution"`
	Balance     float64     `json:"balance"`
	IsExternal  bool        `json:"isExternal"`
}

type AccountContribution struct {
	AccountType       AccountType `json:"accountType"`
	AnnualLimit       float64     `json:"annualLimit"`
	LifetimeCap       *float64    `json:"lifetimeCap,omitempty"`
	Contributed       float64     `json:"contributed"`
	Remaining         float64     `json:"remaining"`
	IsOverContributed bool        `json:"isOverContributed"`
	OverAmount        *float64    `json:"overAmount,omitempty"`
	PenaltyPerMonth   *float64    `json:"penaltyPerMonth,omitempty"`
	Deadline          *time.Time  `json:"deadline,omitempty"`
	DaysUntilDeadline *int32      `json:"daysUntilDeadline,omitempty"`
}

type ActionItem struct {
	ID             string           `json:"id"`
	Client         *Client          `json:"client"`
	Alert          *Alert           `json:"alert,omitempty"`
	Text           string           `json:"text"`
	Status         ActionItemStatus `json:"status"`
	DueDate        *time.Time       `json:"dueDate,omitempty"`
	CreatedAt      time.Time        `json:"createdAt"`
	ResolvedAt     *time.Time       `json:"resolvedAt,omitempty"`
	ResolutionNote *string          `json:"resolutionNote,omitempty"`
}

type Advisor struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Role  string `json:"role"`
}

type AdvisorNote struct {
	ID   string    `json:"id"`
	Date time.Time `json:"date"`
	Text string    `json:"text"`
}

type Alert struct {
	ID                string        `json:"id"`
	ConditionKey      string        `json:"conditionKey"`
	Client            *Client       `json:"client"`
	Severity          AlertSeverity `json:"severity"`
	Category          string        `json:"category"`
	Status            AlertStatus   `json:"status"`
	SnoozedUntil      *time.Time    `json:"snoozedUntil,omitempty"`
	Summary           string        `json:"summary"`
	DraftMessage      *string       `json:"draftMessage,omitempty"`
	LinkedActionItems []*ActionItem `json:"linkedActionItems"`
	CreatedAt         time.Time     `json:"createdAt"`
	UpdatedAt         time.Time     `json:"updatedAt"`
}

type AlertEvent struct {
	Type  AlertEventType `json:"type"`
	Alert *Alert         `json:"alert"`
}

type AlertFilter struct {
	Severity *AlertSeverity `json:"severity,omitempty"`
	Status   *AlertStatus   `json:"status,omitempty"`
	ClientID *string        `json:"clientId,omitempty"`
}

type Client struct {
	ID               string         `json:"id"`
	Name             string         `json:"name"`
	Email            string         `json:"email"`
	DateOfBirth      time.Time      `json:"dateOfBirth"`
	Household        *Household     `json:"household,omitempty"`
	Accounts         []*Account     `json:"accounts"`
	ExternalAccounts []*Account     `json:"externalAccounts"`
	Aum              float64        `json:"aum"`
	LastMeeting      time.Time      `json:"lastMeeting"`
	Health           HealthStatus   `json:"health"`
	Alerts           []*Alert       `json:"alerts"`
	ActionItems      []*ActionItem  `json:"actionItems"`
	Goals            []*Goal        `json:"goals"`
	Notes            []*AdvisorNote `json:"notes"`
}

type ContributionSummary struct {
	ClientID string                 `json:"clientId"`
	TaxYear  int32                  `json:"taxYear"`
	Accounts []*AccountContribution `json:"accounts"`
}

type CreateActionItemInput struct {
	ClientID string     `json:"clientId"`
	AlertID  *string    `json:"alertId,omitempty"`
	Text     string     `json:"text"`
	DueDate  *time.Time `json:"dueDate,omitempty"`
}

type Goal struct {
	ID           string     `json:"id"`
	Name         string     `json:"name"`
	TargetAmount *float64   `json:"targetAmount,omitempty"`
	TargetDate   *time.Time `json:"targetDate,omitempty"`
	ProgressPct  int32      `json:"progressPct"`
	Status       GoalStatus `json:"status"`
}

type Household struct {
	ID      string    `json:"id"`
	Name    string    `json:"name"`
	Members []*Client `json:"members"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type SweepResult struct {
	AlertsGenerated int32  `json:"alertsGenerated"`
	AlertsUpdated   int32  `json:"alertsUpdated"`
	AlertsSkipped   int32  `json:"alertsSkipped"`
	Duration        string `json:"duration"`
}

type Transfer struct {
	ID                 string         `json:"id"`
	Client             *Client        `json:"client"`
	SourceInstitution  string         `json:"sourceInstitution"`
	AccountType        AccountType    `json:"accountType"`
	Amount             float64        `json:"amount"`
	Status             TransferStatus `json:"status"`
	InitiatedAt        time.Time      `json:"initiatedAt"`
	DaysInCurrentStage int32          `json:"daysInCurrentStage"`
	IsStuck            bool           `json:"isStuck"`
}

type UpdateActionItemInput struct {
	Text    *string           `json:"text,omitempty"`
	Status  *ActionItemStatus `json:"status,omitempty"`
	DueDate *time.Time        `json:"dueDate,omitempty"`
}

type AccountType string

const (
	AccountTypeRrsp   AccountType = "RRSP"
	AccountTypeTfsa   AccountType = "TFSA"
	AccountTypeFhsa   AccountType = "FHSA"
	AccountTypeResp   AccountType = "RESP"
	AccountTypeNonReg AccountType = "NON_REG"
)

var AllAccountType = []AccountType{
	AccountTypeRrsp,
	AccountTypeTfsa,
	AccountTypeFhsa,
	AccountTypeResp,
	AccountTypeNonReg,
}

func (e AccountType) IsValid() bool {
	switch e {
	case AccountTypeRrsp, AccountTypeTfsa, AccountTypeFhsa, AccountTypeResp, AccountTypeNonReg:
		return true
	}
	return false
}

func (e AccountType) String() string {
	return string(e)
}

func (e *AccountType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccountType", str)
	}
	return nil
}

func (e AccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccountType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccountType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ActionItemStatus string

const (
	ActionItemStatusPending    ActionItemStatus = "PENDING"
	ActionItemStatusInProgress ActionItemStatus = "IN_PROGRESS"
	ActionItemStatusDone       ActionItemStatus = "DONE"
	ActionItemStatusClosed     ActionItemStatus = "CLOSED"
)

var AllActionItemStatus = []ActionItemStatus{
	ActionItemStatusPending,
	ActionItemStatusInProgress,
	ActionItemStatusDone,
	ActionItemStatusClosed,
}

func (e ActionItemStatus) IsValid() bool {
	switch e {
	case ActionItemStatusPending, ActionItemStatusInProgress, ActionItemStatusDone, ActionItemStatusClosed:
		return true
	}
	return false
}

func (e ActionItemStatus) String() string {
	return string(e)
}

func (e *ActionItemStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ActionItemStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ActionItemStatus", str)
	}
	return nil
}

func (e ActionItemStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ActionItemStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ActionItemStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AlertEventType string

const (
	AlertEventTypeCreated AlertEventType = "CREATED"
	AlertEventTypeUpdated AlertEventType = "UPDATED"
	AlertEventTypeClosed  AlertEventType = "CLOSED"
)

var AllAlertEventType = []AlertEventType{
	AlertEventTypeCreated,
	AlertEventTypeUpdated,
	AlertEventTypeClosed,
}

func (e AlertEventType) IsValid() bool {
	switch e {
	case AlertEventTypeCreated, AlertEventTypeUpdated, AlertEventTypeClosed:
		return true
	}
	return false
}

func (e AlertEventType) String() string {
	return string(e)
}

func (e *AlertEventType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertEventType", str)
	}
	return nil
}

func (e AlertEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertEventType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertEventType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AlertSeverity string

const (
	AlertSeverityCritical AlertSeverity = "CRITICAL"
	AlertSeverityUrgent   AlertSeverity = "URGENT"
	AlertSeverityAdvisory AlertSeverity = "ADVISORY"
	AlertSeverityInfo     AlertSeverity = "INFO"
)

var AllAlertSeverity = []AlertSeverity{
	AlertSeverityCritical,
	AlertSeverityUrgent,
	AlertSeverityAdvisory,
	AlertSeverityInfo,
}

func (e AlertSeverity) IsValid() bool {
	switch e {
	case AlertSeverityCritical, AlertSeverityUrgent, AlertSeverityAdvisory, AlertSeverityInfo:
		return true
	}
	return false
}

func (e AlertSeverity) String() string {
	return string(e)
}

func (e *AlertSeverity) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertSeverity(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertSeverity", str)
	}
	return nil
}

func (e AlertSeverity) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertSeverity) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertSeverity) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AlertStatus string

const (
	AlertStatusOpen    AlertStatus = "OPEN"
	AlertStatusSnoozed AlertStatus = "SNOOZED"
	AlertStatusActed   AlertStatus = "ACTED"
	AlertStatusClosed  AlertStatus = "CLOSED"
)

var AllAlertStatus = []AlertStatus{
	AlertStatusOpen,
	AlertStatusSnoozed,
	AlertStatusActed,
	AlertStatusClosed,
}

func (e AlertStatus) IsValid() bool {
	switch e {
	case AlertStatusOpen, AlertStatusSnoozed, AlertStatusActed, AlertStatusClosed:
		return true
	}
	return false
}

func (e AlertStatus) String() string {
	return string(e)
}

func (e *AlertStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AlertStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AlertStatus", str)
	}
	return nil
}

func (e AlertStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AlertStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AlertStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type GoalStatus string

const (
	GoalStatusOnTrack GoalStatus = "ON_TRACK"
	GoalStatusBehind  GoalStatus = "BEHIND"
	GoalStatusAhead   GoalStatus = "AHEAD"
)

var AllGoalStatus = []GoalStatus{
	GoalStatusOnTrack,
	GoalStatusBehind,
	GoalStatusAhead,
}

func (e GoalStatus) IsValid() bool {
	switch e {
	case GoalStatusOnTrack, GoalStatusBehind, GoalStatusAhead:
		return true
	}
	return false
}

func (e GoalStatus) String() string {
	return string(e)
}

func (e *GoalStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GoalStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GoalStatus", str)
	}
	return nil
}

func (e GoalStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *GoalStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e GoalStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type HealthStatus string

const (
	HealthStatusGreen  HealthStatus = "GREEN"
	HealthStatusYellow HealthStatus = "YELLOW"
	HealthStatusRed    HealthStatus = "RED"
)

var AllHealthStatus = []HealthStatus{
	HealthStatusGreen,
	HealthStatusYellow,
	HealthStatusRed,
}

func (e HealthStatus) IsValid() bool {
	switch e {
	case HealthStatusGreen, HealthStatusYellow, HealthStatusRed:
		return true
	}
	return false
}

func (e HealthStatus) String() string {
	return string(e)
}

func (e *HealthStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = HealthStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid HealthStatus", str)
	}
	return nil
}

func (e HealthStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *HealthStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e HealthStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TransferStatus string

const (
	TransferStatusInitiated          TransferStatus = "INITIATED"
	TransferStatusDocumentsSubmitted TransferStatus = "DOCUMENTS_SUBMITTED"
	TransferStatusInReview           TransferStatus = "IN_REVIEW"
	TransferStatusInTransit          TransferStatus = "IN_TRANSIT"
	TransferStatusReceived           TransferStatus = "RECEIVED"
	TransferStatusInvested           TransferStatus = "INVESTED"
)

var AllTransferStatus = []TransferStatus{
	TransferStatusInitiated,
	TransferStatusDocumentsSubmitted,
	TransferStatusInReview,
	TransferStatusInTransit,
	TransferStatusReceived,
	TransferStatusInvested,
}

func (e TransferStatus) IsValid() bool {
	switch e {
	case TransferStatusInitiated, TransferStatusDocumentsSubmitted, TransferStatusInReview, TransferStatusInTransit, TransferStatusReceived, TransferStatusInvested:
		return true
	}
	return false
}

func (e TransferStatus) String() string {
	return string(e)
}

func (e *TransferStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransferStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransferStatus", str)
	}
	return nil
}

func (e TransferStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TransferStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TransferStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
