#!/bin/bash
set -e

# AdvisorHub — Middle Loop
# Reads manifest.yaml, processes contexts in dependency order.
# For each context: branch → dispatch Claude Code → test → commit → PR
#
# Prerequisites:
#   - yq (brew install yq)
#   - gh CLI (brew install gh), authenticated
#   - claude CLI (Claude Code)
#   - On main branch, clean working tree

MANIFEST="manifest.yaml"
LEDGER="docs/WORK_LEDGER.md"
BASE_BRANCH="main"

# --- Preflight checks ---

if [ ! -f "$MANIFEST" ]; then
  echo "ERROR: $MANIFEST not found"
  exit 1
fi

if ! command -v yq &> /dev/null; then
  echo "ERROR: yq not found. Install with: brew install yq"
  exit 1
fi

if ! command -v gh &> /dev/null; then
  echo "ERROR: gh CLI not found. Install with: brew install gh"
  exit 1
fi

if ! command -v claude &> /dev/null; then
  echo "ERROR: claude CLI not found"
  exit 1
fi

# Ensure clean working tree
if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: Working tree is not clean. Commit or stash changes first."
  exit 1
fi

# Ensure we're on base branch
current_branch=$(git branch --show-current)
if [ "$current_branch" != "$BASE_BRANCH" ]; then
  echo "ERROR: Not on $BASE_BRANCH branch (on $current_branch). Switch first."
  exit 1
fi

# --- Initialize ledger ---

build_start=$(date -u +%Y-%m-%dT%H:%M:%SZ)

cat > "$LEDGER" << EOF
# Work Ledger — AdvisorHub Build

Build started: $build_start

| Context | Risk | Duration | Tests | Review | Status |
|---------|------|----------|-------|--------|--------|
EOF

echo ""
echo "Build started: $build_start"
echo ""

# --- Read manifest ---

context_count=$(yq '.contexts | length' "$MANIFEST")
human_reviews=0
auto_approved=0

for i in $(seq 0 $((context_count - 1))); do
  name=$(yq ".contexts[$i].name" "$MANIFEST")
  spec=$(yq ".contexts[$i].spec" "$MANIFEST")
  risk=$(yq ".contexts[$i].risk" "$MANIFEST")
  pkg=$(yq ".contexts[$i].package" "$MANIFEST")
  ctx_type=$(yq ".contexts[$i].type" "$MANIFEST")
  description=$(yq ".contexts[$i].description" "$MANIFEST")

  echo "═══════════════════════════════════════"
  echo "  Context: $name"
  echo "  Risk:    $risk"
  echo "  Spec:    $spec"
  echo "  Desc:    $description"
  echo "═══════════════════════════════════════"

  start_time=$(date +%s)
  branch_name="feat/$name"

  # --- Create branch ---

  git checkout -b "$branch_name" "$BASE_BRANCH" 2>/dev/null || {
    echo "Branch $branch_name already exists. Checking out..."
    git checkout "$branch_name"
  }

  # --- Dispatch Claude Code (inner loop) ---

  echo ""
  echo "Dispatching Claude Code for $name..."
  echo ""

  claude --dangerously-skip-permissions -p "/implement-spec $name" 2>&1 | tee "/tmp/autodev-$name.log"

  # --- Run tests ---

  echo ""
  echo "Running tests for $name..."
  echo ""

  if [ "$ctx_type" = "node" ]; then
    # Frontend: build to verify, then run tests if they exist
    test_output=$(cd frontend && npm run build 2>&1) || {
      echo "BUILD FAILED for $name"
      echo "$test_output"
      echo "| $name | $risk | — | FAIL | — | FAILED |" >> "$LEDGER"
      git checkout "$BASE_BRANCH"
      echo ""
      echo "Stopping build. Fix $name and re-run."
      exit 1
    }
    echo "Build succeeded."
    test_count="build-ok"
  else
    # Go: run unit tests (go.mod is in backend/)
    pkg_dir="$pkg"
    test_output=$(cd backend && go test ./internal/"$pkg_dir"/... -v -count=1 2>&1) || {
      echo "TESTS FAILED for $name"
      echo "$test_output"
      echo "| $name | $risk | — | FAIL | — | FAILED |" >> "$LEDGER"
      git checkout "$BASE_BRANCH"
      echo ""
      echo "Stopping build. Fix $name and re-run."
      exit 1
    }

    # Count tests from output
    test_count=$(echo "$test_output" | grep -c "^--- PASS" || echo "0")
    echo "Tests passed: $test_count"
  fi

  # --- Commit ---

  git add -A
  git commit -m "$(cat <<EOF
feat($name): implement $name bounded context [risk:$risk]

$description

Co-Authored-By: Claude Code <noreply@anthropic.com>
EOF
  )"

  # --- Push + PR ---

  git push -u origin "$branch_name"

  pr_url=$(gh pr create \
    --title "feat($name): implement $name [risk:$risk]" \
    --body "$(cat <<EOF
## Summary

Implements the **$name** bounded context.

- **Risk:** $risk
- **Spec:** \`$spec\`
- **Description:** $description
- **Tests:** $test_count passed

## Review guidance

$(if [ "$risk" = "HIGH" ]; then
  echo "**HIGH RISK** — requires careful human review before merge. Check business logic, state transitions, and edge cases against the spec."
elif [ "$risk" = "MEDIUM" ]; then
  echo "**MEDIUM RISK** — skim for correctness. Focus on integration points and contracts."
else
  echo "**LOW RISK** — auto-merge candidate if tests pass."
fi)

## Test plan

- [ ] All test anchors from spec are covered
- [ ] \`go test ./backend/internal/$pkg_dir/...\` passes
- [ ] \`go vet ./backend/internal/$pkg_dir/...\` passes

Generated by autodev.sh
EOF
  )" 2>&1)

  echo "PR created: $pr_url"

  # --- Risk-tier gate ---

  end_time=$(date +%s)
  duration=$(( (end_time - start_time) / 60 ))

  if [ "$risk" = "HIGH" ]; then
    human_reviews=$((human_reviews + 1))
    echo ""
    echo "HIGH RISK — Review PR before continuing: $pr_url"
    echo "Press enter after reviewing and merging, or Ctrl+C to abort."
    read -r
    review_status="Human-reviewed"
  elif [ "$risk" = "MEDIUM" ]; then
    human_reviews=$((human_reviews + 1))
    echo ""
    echo "MEDIUM RISK — Skim PR: $pr_url"
    echo "Press enter to continue, or Ctrl+C to abort."
    read -r
    review_status="Skimmed"
  else
    # LOW risk: auto-merge
    echo "LOW RISK — Auto-merging..."
    gh pr merge "$pr_url" --merge --delete-branch
    review_status="Auto"
    auto_approved=$((auto_approved + 1))
  fi

  # --- Run migrations if any were added ---

  migration_files=$(git diff "$BASE_BRANCH"..."$branch_name" --name-only -- backend/migrations/*.sql 2>/dev/null)
  if [ -n "$migration_files" ]; then
    echo "Running migrations against Railway Postgres..."
    cat backend/migrations/*.sql | railway connect Postgres
    echo "Migrations applied."
  else
    echo "No new migrations for $name, skipping."
  fi

  # --- Return to base branch ---

  git checkout "$BASE_BRANCH"
  git pull origin "$BASE_BRANCH"

  # --- Log to ledger ---

  echo "| $name | $risk | ${duration}m | $test_count | $review_status | DONE |" >> "$LEDGER"

  echo ""
  echo "Completed: $name (${duration}m)"
  echo ""
done

# --- Finalize ledger ---

build_end=$(date -u +%Y-%m-%dT%H:%M:%SZ)

cat >> "$LEDGER" << EOF

Build completed: $build_end
Total contexts: $context_count
Human reviews: $human_reviews
Auto-approved: $auto_approved
EOF

echo "═══════════════════════════════════════"
echo "  Build complete!"
echo "  Contexts: $context_count"
echo "  Human reviews: $human_reviews"
echo "  Auto-approved: $auto_approved"
echo "  Ledger: $LEDGER"
echo "═══════════════════════════════════════"
