package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"time"

	"github.com/swatkatz/advisorhub/backend/internal/graph/model"
)

// Client is the resolver for the client field.
func (r *actionItemResolver) Client(ctx context.Context, obj *model.ActionItem) (*model.Client, error) {
	panic(fmt.Errorf("not implemented: Client - client"))
}

// Alert is the resolver for the alert field.
func (r *actionItemResolver) Alert(ctx context.Context, obj *model.ActionItem) (*model.Alert, error) {
	panic(fmt.Errorf("not implemented: Alert - alert"))
}

// Client is the resolver for the client field.
func (r *alertResolver) Client(ctx context.Context, obj *model.Alert) (*model.Client, error) {
	panic(fmt.Errorf("not implemented: Client - client"))
}

// LinkedActionItems is the resolver for the linkedActionItems field.
func (r *alertResolver) LinkedActionItems(ctx context.Context, obj *model.Alert) ([]*model.ActionItem, error) {
	panic(fmt.Errorf("not implemented: LinkedActionItems - linkedActionItems"))
}

// Household is the resolver for the household field.
func (r *clientResolver) Household(ctx context.Context, obj *model.Client) (*model.Household, error) {
	panic(fmt.Errorf("not implemented: Household - household"))
}

// Accounts is the resolver for the accounts field.
func (r *clientResolver) Accounts(ctx context.Context, obj *model.Client) ([]*model.Account, error) {
	panic(fmt.Errorf("not implemented: Accounts - accounts"))
}

// ExternalAccounts is the resolver for the externalAccounts field.
func (r *clientResolver) ExternalAccounts(ctx context.Context, obj *model.Client) ([]*model.Account, error) {
	panic(fmt.Errorf("not implemented: ExternalAccounts - externalAccounts"))
}

// Aum is the resolver for the aum field.
func (r *clientResolver) Aum(ctx context.Context, obj *model.Client) (float64, error) {
	panic(fmt.Errorf("not implemented: Aum - aum"))
}

// Health is the resolver for the health field.
func (r *clientResolver) Health(ctx context.Context, obj *model.Client) (model.HealthStatus, error) {
	panic(fmt.Errorf("not implemented: Health - health"))
}

// Alerts is the resolver for the alerts field.
func (r *clientResolver) Alerts(ctx context.Context, obj *model.Client) ([]*model.Alert, error) {
	panic(fmt.Errorf("not implemented: Alerts - alerts"))
}

// ActionItems is the resolver for the actionItems field.
func (r *clientResolver) ActionItems(ctx context.Context, obj *model.Client) ([]*model.ActionItem, error) {
	panic(fmt.Errorf("not implemented: ActionItems - actionItems"))
}

// Goals is the resolver for the goals field.
func (r *clientResolver) Goals(ctx context.Context, obj *model.Client) ([]*model.Goal, error) {
	panic(fmt.Errorf("not implemented: Goals - goals"))
}

// Notes is the resolver for the notes field.
func (r *clientResolver) Notes(ctx context.Context, obj *model.Client) ([]*model.AdvisorNote, error) {
	panic(fmt.Errorf("not implemented: Notes - notes"))
}

// Members is the resolver for the members field.
func (r *householdResolver) Members(ctx context.Context, obj *model.Household) ([]*model.Client, error) {
	panic(fmt.Errorf("not implemented: Members - members"))
}

// SendAlert is the resolver for the sendAlert field.
func (r *mutationResolver) SendAlert(ctx context.Context, alertID string, message *string) (*model.Alert, error) {
	panic(fmt.Errorf("not implemented: SendAlert - sendAlert"))
}

// TrackAlert is the resolver for the trackAlert field.
func (r *mutationResolver) TrackAlert(ctx context.Context, alertID string, actionItemText string) (*model.Alert, error) {
	panic(fmt.Errorf("not implemented: TrackAlert - trackAlert"))
}

// SnoozeAlert is the resolver for the snoozeAlert field.
func (r *mutationResolver) SnoozeAlert(ctx context.Context, alertID string, until *time.Time) (*model.Alert, error) {
	panic(fmt.Errorf("not implemented: SnoozeAlert - snoozeAlert"))
}

// AcknowledgeAlert is the resolver for the acknowledgeAlert field.
func (r *mutationResolver) AcknowledgeAlert(ctx context.Context, alertID string) (*model.Alert, error) {
	panic(fmt.Errorf("not implemented: AcknowledgeAlert - acknowledgeAlert"))
}

// CreateActionItem is the resolver for the createActionItem field.
func (r *mutationResolver) CreateActionItem(ctx context.Context, input model.CreateActionItemInput) (*model.ActionItem, error) {
	panic(fmt.Errorf("not implemented: CreateActionItem - createActionItem"))
}

// UpdateActionItem is the resolver for the updateActionItem field.
func (r *mutationResolver) UpdateActionItem(ctx context.Context, id string, input model.UpdateActionItemInput) (*model.ActionItem, error) {
	panic(fmt.Errorf("not implemented: UpdateActionItem - updateActionItem"))
}

// AddNote is the resolver for the addNote field.
func (r *mutationResolver) AddNote(ctx context.Context, clientID string, text string) (*model.AdvisorNote, error) {
	panic(fmt.Errorf("not implemented: AddNote - addNote"))
}

// RunMorningSweep is the resolver for the runMorningSweep field.
func (r *mutationResolver) RunMorningSweep(ctx context.Context, advisorID string) (*model.SweepResult, error) {
	panic(fmt.Errorf("not implemented: RunMorningSweep - runMorningSweep"))
}

// Advisor is the resolver for the advisor field.
func (r *queryResolver) Advisor(ctx context.Context, id string) (*model.Advisor, error) {
	panic(fmt.Errorf("not implemented: Advisor - advisor"))
}

// Clients is the resolver for the clients field.
func (r *queryResolver) Clients(ctx context.Context, advisorID string) ([]*model.Client, error) {
	panic(fmt.Errorf("not implemented: Clients - clients"))
}

// Client is the resolver for the client field.
func (r *queryResolver) Client(ctx context.Context, id string) (*model.Client, error) {
	panic(fmt.Errorf("not implemented: Client - client"))
}

// Alerts is the resolver for the alerts field.
func (r *queryResolver) Alerts(ctx context.Context, advisorID string, filter *model.AlertFilter) ([]*model.Alert, error) {
	panic(fmt.Errorf("not implemented: Alerts - alerts"))
}

// Alert is the resolver for the alert field.
func (r *queryResolver) Alert(ctx context.Context, id string) (*model.Alert, error) {
	panic(fmt.Errorf("not implemented: Alert - alert"))
}

// ContributionSummary is the resolver for the contributionSummary field.
func (r *queryResolver) ContributionSummary(ctx context.Context, clientID string, taxYear int32) (*model.ContributionSummary, error) {
	panic(fmt.Errorf("not implemented: ContributionSummary - contributionSummary"))
}

// Transfers is the resolver for the transfers field.
func (r *queryResolver) Transfers(ctx context.Context, advisorID string) ([]*model.Transfer, error) {
	panic(fmt.Errorf("not implemented: Transfers - transfers"))
}

// ActionItems is the resolver for the actionItems field.
func (r *queryResolver) ActionItems(ctx context.Context, clientID *string) ([]*model.ActionItem, error) {
	panic(fmt.Errorf("not implemented: ActionItems - actionItems"))
}

// AlertFeed is the resolver for the alertFeed field.
func (r *subscriptionResolver) AlertFeed(ctx context.Context, advisorID string) (<-chan *model.AlertEvent, error) {
	panic(fmt.Errorf("not implemented: AlertFeed - alertFeed"))
}

// Client is the resolver for the client field.
func (r *transferResolver) Client(ctx context.Context, obj *model.Transfer) (*model.Client, error) {
	panic(fmt.Errorf("not implemented: Client - client"))
}

// ActionItem returns ActionItemResolver implementation.
func (r *Resolver) ActionItem() ActionItemResolver { return &actionItemResolver{r} }

// Alert returns AlertResolver implementation.
func (r *Resolver) Alert() AlertResolver { return &alertResolver{r} }

// Client returns ClientResolver implementation.
func (r *Resolver) Client() ClientResolver { return &clientResolver{r} }

// Household returns HouseholdResolver implementation.
func (r *Resolver) Household() HouseholdResolver { return &householdResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

// Transfer returns TransferResolver implementation.
func (r *Resolver) Transfer() TransferResolver { return &transferResolver{r} }

type actionItemResolver struct{ *Resolver }
type alertResolver struct{ *Resolver }
type clientResolver struct{ *Resolver }
type householdResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
type transferResolver struct{ *Resolver }
